/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */

plugins {
  application
}

repositories {
  mavenCentral()
}

sourceSets {
  main {
    java {
      setSrcDirs(listOf("."))
    }
  }
}

dependencies {
  implementation("info.picocli:picocli:4.7.6")
}

application {
  mainClass = "Program"
}
