services:
  rps:
    build: .
    volumes:
      - ./app/config:/root/config
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
