/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */

plugins {
  application
  id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("info.picocli:picocli:4.7.6")

  testImplementation("org.junit.jupiter:junit-jupiter:5.10.3")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

javafx {
    version = "23.0.1"
    modules("javafx.controls")
}

application {
  mainClass = "Program"
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}
