name: "Java"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version: [8, 17, 21]

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: "Build project"
        run: ./gradlew build
